apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project2
secretGenerator:
- name: db-info
  literals:
  - host=mysql-service:3306
  - root_password=root!
  - database=wordpress
  - user=wordpress
  - password=wordpress
resources:
  - mysql.yaml
  - wordpress.yaml
