apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-lapi-secrets-external
  namespace: crowdsec
type: Opaque
stringData:
  csLapiSecret: "<원하는 고정값>"
  registrationToken: "<원하는 고정값>"

CS_LAPI_SECRET="$(openssl rand -hex 32)"
