container_runtime: containerd

agent:
  extraVolumes:
    - name: varlog-containers
      hostPath:
        path: /var/log/containers
    - name: varlog-pods
      hostPath:
        path: /var/log/pods

  extraVolumeMounts:
    - name: varlog-containers
      mountPath: /var/log/containers
      readOnly: true
    - name: varlog-pods
      mountPath: /var/log/pods
      readOnly: true

  acquisition:
    - namespace: traefik
      podName: "traefik-*"
      program: traefik
      poll_without_inotify: true

  env:
    - name: COLLECTIONS
      value: "crowdsecurity/traefik crowdsecurity/base-http-scenarios crowdsecurity/http-cve crowdsecurity/wordpress crowdsecurity/nextcloud"

lapi:
  persistentVolume:
    data:
      enabled: true
      storageClassName: rook-rbd-sc
      accessModes:
        - ReadWriteOnce
      size: 1Gi
    config:
      enabled: true
      storageClassName: rook-rbd-sc
      accessModes:
        - ReadWriteOnce
      size: 100Mi

config:
  api:
    server:
      offline_timeout: 6h
