apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: rook-store
  namespace: rook-ceph
spec:
  preservePoolsOnDelete: true

  metadataPool:
    failureDomain: host
    replicated:
      size: 3

  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 2
      codingChunks: 1

  gateway:
    port: 80
    instances: 2
