---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB3jLeoxYmeRD3RKoMv9NJrSTbqRgbxttL3OyODJi1RwiZ/qqq5mvc6oGf3fKj39mIvEvXl1GxuCqG+eGlR7JWpC+KLS6OdtN1swov+uwi/8FWVyhKqqQIElqRGbkh9+vEtSvA680OqTl0ExsbjpOIWCiDEu0rdDI91jKv9H8tSuiu2/rt88nEaeVs1GLgCQ4/2dalbB6g9cN/ZLXPsIO+mDByW5vCd5eXI0x3HFT7++rcrTlVpIGh4tzNLk46Dtn4CbWfQAYc0YrvloBRzMqdyid77tSqIz4AmTPTe4G5dN7pyuDF1If68qjUjHeFE/nMi0W58FnKS4br6CYhc3dZ3uHB7JVaaprp+YKapagY2+jCIpuWRep/7VfoAf9jQfaTvCYzzwRXBRkf1R17eplBjQM+JOLPXkf+HO7EJJOqpK6Lrn+Jo2fw1x9gSqySRWVeNKb3ZYM0Lp+khK/e8huAsvQemkYLnH5YyAKYZAiOuvVNlHprsdbsmxv5S0sEIODu6ZyglNkPqgAIx/8gw+VuC3a96Lr6xk09BPd7BWYcaUvB3uPR1pMvNk7lEAq/bRUNkejwbY6pv+HJh3KBi4O+Pg47mipjr/EUZQMkjLx3kbA2VcR6mCUM4vn7fibaS0zx5kAZlMNV/gAb5fr5uxEMco3nCF0l1rLvbh/cdukVFMStQKgVdzovDtUT9v9NhhZ/f6PYR
    admin-user: AgCbbkXTUjL4zLpZmK+OQTnrNk6qXBUvYriee3J9qKQbmHXLkK3rrnWHIbPzgUWoPt4uW3FPmw1wJJC5A7ngWXJsBj2XEQy12auxec/+aA4wErLTLVt1t8ZPwpJk62bA8EC3YzRizK7vVhlvycwoXpsIR5wXoE2ZVMwK4tQ4i+IBvsCn6Ihg8miHkb5t24dUkco/qjeW4oZ4QiTtnhBNAWGiMwSpbXz3JeT/VEAXAUjjeVLfuVp4Dj1ccZRqOmoodIv6XdF8PkPClDhNKDS/Myn4rYHkh00xOfiaHcDrF38hfeaFR2x40hi6iEPS+MsPgEmMaimLs66BXZCLGhz5BlWa578Mj3sqvKP4YU4Zkf03JC++d29o5LOzBWIDWVOxJWR/Ef1L7quW/fp3pTPVPlNNPMnJaa7Awvc6qP4rPyPY3262Ygrlf7dXmCfo4kxPBG/WxUeEynAEouXbjGcbJhrGr05vdX0ms7Rqq+6RnnVpOVT0RHii4os5WKw3J9OZaEukal81Adg3BYtc7TNquuQYCgQ7JcZu+DHY7sjkEGMoZsONkmK7a8pWv0TCf3LG7PKw+mR009n0AmU2v/6nvnBnqEgsL3J94oTSQtU9NlP+7+Gqz0AB8DTB9b5gNiVraFPCch4jHGAd+LeyDH0QNNGeQpY9w3FN80ESAetHYc8d+jaVgGubQDGJQzBcosz4Zilm5FTV
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
