pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Verify') {
            steps {
                sh '''
                pwd
                ls -al
                git branch
                git log --oneline -3
                '''
            }
        }

        stage('Hello') {
            steps {
                echo 'Hello Jenkins SCM'
            }
        }

        #stage('Fail Test') {
        #    steps {
        #        sh 'exit 1'
        #    }
        #}
    }

    post {
        success {
            echo 'BUILD SUCCESS'
        }

        #failure {
        #    echo 'BUILD FAILURE'
        #}
        
        always {
            echo 'ALWAYS RUN'
        }

    }
}
