pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Timeout Test') {
            steps {
                retry(3) {
                    timeout(time: 30, unit: 'SECONDS') {
                        sh 'sleep 5'
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'BUILD SUCCESS'
        }

        failure {
            echo 'BUILD FAILURE'
        }
        
        always {
            echo 'ALWAYS RUN'
        }

    }
}
