apiVersion: batch/v1
kind: Job
metadata:
  name: rgw-create-loki-buckets
  namespace: rook-ceph
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: minio/mc:latest
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-object-user-rook-store-loki-store-user
                  key: AccessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-object-user-rook-store-loki-store-user
                  key: SecretKey
          command: ["/bin/sh","-c"]
          args:
            - |
              set -e
              mc alias set rgw http://rook-ceph-rgw-rook-store.rook-ceph.svc:80 "$AWS_ACCESS_KEY_ID" "$AWS_SECRET_ACCESS_KEY"
              mc mb --ignore-existing rgw/loki-chunks
              mc mb --ignore-existing rgw/loki-ruler
              mc mb --ignore-existing rgw/loki-admin
              mc ls rgw
