apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-ui
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prometheus.lucky-gun.com`)
      kind: Rule
      services:
        - name: prometheus-stack-kube-prom-prometheus
          port: 9090
          namespace: monitoring
  tls:
    certResolver: myresolver
    options:
      name: infra-tls
      namespace: traefik
