apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps

secretGenerator:
- name: nextcloud-secrets
  envs:
  - .env

configMapGenerator:
- name: nextcloud-config
  literals:
    - REDIS_HOST=redis-service.database.svc.cluster.local

resources:
- nextcloud.yaml
- registry-sealed-secret.yaml
