---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: apps
spec:
  encryptedData:
    .dockerconfigjson: AgB6XYsBukq8jnqrykmYR/tiUPiZxR8n97wa6IlIbabwUhqXEb9VlcrumoYh8NjyrddYkcvQdaZCsXXE8X5SFv/G/ufd6EiGxs77CIgdrqiKYZHdnCGTErLSrNG5OtJ7AHLTq6Wow50w4GXcRESxlzfPxOJ3tUyPJ778IjbuzSm+33ifcwVqzr9euWFI31hflUwmb2VgH5Yuifw2JSADr0hrS4tQL2n/+YjNNIby8gRE4gPqkbv4ASA3ic5ArCOQN05RFlrTE279ufabMtrYLEQ3VH2KWwPMOVy6hVvU9NcB/2SNxfDuJbeTs/jz0yx5Nj2PnUGQzkAsiSXqdvoNAH/Z7MHS87EmBa2Ngc7NykS4CIUQ4VpqhuDoXGj37T5E0hM3dUIEoQMLTjuuVfEMimE2TFXmcX6MNiRmKdrql4VWLhg5JeHz53RlKEk8OsuodjiGAgmHf+o45uS6Wf31GJBPM9sC4f3sNG4/YOqvjleuefxtJJ+1E5KKgbmRKTscjxYuv7MujWxwXcqSO1aZT/f1r9SGdUILm4GQIsnoepdYaSH7r/PE1A2MuF0O6euZSb27+FhCNeCTBnOrIWnB1eKPYaW5rQxFjgafvcjxdpvP0HcH/yT1OnFIvn5Mm54CtwSzECoTQNIfgsRMqwjS203CFc66IDyzkUCnqUuSsdrnC83d2tizdxh11S7sEvrnUFrFwS8TrxYMQrt+n+tjtHklZ8YoUdSxbyX80KfYtH0FQpB4CTCzf8/SndUjbBOwuIRkVk6usSOixrdlfTtemjQ0xcmP6DJovvIhXMN4lgFvdgUBRX0DSl1+haaMBrBMcH8Bg645mvFtIpNWbiFGwIjm1lI4UxEb+9cQJYk9AxbCWpccFRe/4imWQNC3hEBpzZ9jBhTq2IOGVTq/lo3UPABGRLSKRYl8eP1+8qmC
  template:
    metadata:
      name: regcred
      namespace: apps
    type: kubernetes.io/dockerconfigjson
