---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: infra
spec:
  encryptedData:
    .dockerconfigjson: AgCrWm/fk/jJEg20ih+Gnz5+UGs8WRtypLIWmWTWPp4lAMfT3nssU6tuGHfDpGweJSv8DfKmOyCs3VXaygCoy5ahsZChd8hIa2lUQobyJY5uHEd4tp2iBgY5N/xM6Xou+/01jHLM6TSkrg+f8QkfiuM4gcMgGlrjd1G7aXw9Ytmaw/2CNwSl6Y6+mlPxc6sc70nOTi2yy6dRPo444/SMF+QJ8IYD63cOJWYWsFBnJZ3Enp3B7WCHNTjIRydPLGFSOi5A1Lp6W7pRb7S/KieSaONDjK9vDpvILA+XOPD0mKy6Rk78nSMVcoPJpotP8JwBKnJQ0WdPvSpMdwp5SXUege9ijXVHIGtqNsGoCGlnpGYAvkRhFMjAuuIWMCT+1W1Ojy1kp6wcYhzgCGe2rAhYIY1fOZHASFDxJS6OlKKASdBJp04fxHnGX9YCfzVEShpgw1Gld+OmJ/I58N98H3ntaBMGO15jn1grnLrVX6Ei5PlqvxNjwE4qnObCLb/NKAm53+lpgaXExtPcxYEwnFkd8BRSgX4qK9d2s3IvDy+pdwno3OCMBcZ3/yhLcLcAibRQzOXmvZS71hBNilVIJEb2uwI8b8Z3Zf/g78KKV/L6oJcoibjdDiHMz1L6d4TUwxMhqfkJORqF6vwsv1gyPnQqawPGSRUu9LnynHkyrzI2R2rM9vHtP27pfkova0CHpsJpFubRNTylqby8U/vjOzBQABKAcBo87svGsZ2onZukqwOUR5/eWzMIwBWv+63NjWeUFhiZ+/ZjA7FQ4007IShGaiUcVv9qVRPIMh9gDRDk+4NO04dMcRg/UZlqQCVaOd/4DwsmTagnGRcnlbCozzIQV6EWEHxMWFeyV6vR0SVvymnVQ7lqySQp0fAAFFG3FkFkQNeuwV6sT5qM67SVS5OsP4qRBkymDFp6EZ6svzzI
  template:
    metadata:
      name: regcred
      namespace: infra
    type: kubernetes.io/dockerconfigjson
