apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: my-shared-fs
  namespace: rook-ceph
spec:
  # 메타데이터 서버(MDS) 설정: 고가용성을 위해 2개를 띄우되 1개는 대기(Standby)
  metadataServer:
    activeCount: 1
    activeStandby: true
  # 실제 데이터가 저장될 풀 설정 (복제본 3개)
  dataPools:
    - failureDomain: host
      replicated:
        size: 3
  # 파일 시스템 구조 정보가 저장될 풀
  metadataPool:
    replicated:
      size: 3
