apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: rook-cephfs
  namespace: rook-ceph
spec:
  metadataServer:
    activeCount: 1
    activeStandby: true
  dataPools:
    - failureDomain: host
      replicated:
        size: 3
  metadataPool:
    replicated:
      size: 3
