crds:
  enabled: true

csi:
  enableRbdDriver: true
  enableCephfsDriver: true

monitoring:
  enabled: true

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"
