---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-lapi-secrets-external
  namespace: crowdsec
spec:
  encryptedData:
    csLapiSecret: AgCHoEMYHSFU0YxojCd2BOVdSztPDJoUA/XMub8OuTeekDeWmMqsNBWyPpUTUDbeh1YQO49DseK8ZCyC8YpBAE0v2/r+2lHeBX74MuP4nM6MkGn3Goi29e50zW0b3FEY/BmvmFt8XU2w8imgNdsAHqgUP6nISfm+4JCVZr0vIZd1NQlo7bRQXNkuCIKPBAjXQPu6Y9wIBXRZFVMbtm2vH/wAC5NFUKMO8LVEF688iWWhvhUnO7p0Q+6iDCbtxLweR6wxcbGz9ILD6HbKQv/5g1q++I2q+ZhAiFWFpLSWAOh++kr429om7RohlK/pZaRjVQP7ziHqaBSmmLOm+xkqogODUQcpLyEWoyJPnpz8vV32TW5Zh3yvu/GfAGvVH159cVNmeS40d/ftYxe27doUGmAhe4ZCdKbNWZYBiJWc8x7n8HgjiQnMJ3sH81/CC8E83Kup7EqdvGukB+j9/PJ3JCWrfHgPFh5p42mU3okWDBmXM2xv2TVCSBzrw4JwXld11bNBkVyX+uly7nkSJOr0sXcUuDoboJYxqBl/M0h2EGQOE0dblyt7iVvFNtOl1ZYh25p/ASaBaDmPmyBdJ8KbWgWgCo1I1k+nhj7BHYSIQg5dRavSXSqgO8KRT5ax07MWy8tezB8xBmdj6KhwlO5qB7PhthGiIJWlbhxXJR7Auka0t3uUleLOuIK0p9C0nGZjVl+r4/DWnLrjyE+KK17TqoU=
    registrationToken: AgAbBahjQ1AeqJPM85LgPFFOhjJzdTnUN1TkcP2pLPZF8K8tkZeP5A/ft/5oP3QnwnBUZry5W0RlmhqHDGyM/um/ruOUq/DF1fiB0XQ8JR5DDZl7rD5XyY+aTqFHx/LZ9MHgU9AJq2x1dxT+MYfGZys6Kw4CVFI2rTaSSWE3J8GnLGELSxFspD8tQvizVOXE64BvW8QYR6C84Fu07Hb9vyofSRYGBVuk0AICIdfoLf+t4FMklVUjQw3ou4tnl4NqAfAzN4Z5RqfOM8Hmm6BIScP4p3EJ6h4ke3CTdbhhzjHijOVjKbx34rnKMArnJ8Q3HvC2eQQ1g09AINT43SMt3ZTAHFthEhKk+DGiXrf+YhKAMz2Z8UHxoF38mDClw47EAf11oOSiwXv0zhmBtEffiliFB6SmeeTI8LQYZWWS8bIfaKABPpK0b8IyyxVzwrtCF7B4G2nPjxZk07ikW7o+c6f82zwBmkQvXEAo0EGWcS0tE8EUCcGLj1imQGRK+fOr/UzRJMNoEur9CfFaAAr6AkKrSxDckBcOLB246U27+iUqEHeIooFy0TGw7Ncoz3t4A1TCSI7WD245Kyg0UZImZJenXon7ftbJx9p2cGBgA03azly4pMZEqf5aYb/p7RSpZ6snshgo0pPMA8ckMLN431ePWDKkEc9NX2EaHuvFsKMQQb7HfayacdKAX+nLjiGimgvuGiW+OkCgYewe
  template:
    metadata:
      name: crowdsec-lapi-secrets-external
      namespace: crowdsec
    type: Opaque
