---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-lapi-secrets-external
  namespace: crowdsec
spec:
  encryptedData:
    csLapiSecret: AgBvCDVvzdB8gz1T9fBKgdsklNwsfyKPMagF8B6jBxOC2c0pulhomQwzObKXEmpKnp/a0UdQlm9rS+cj1+kkFb1GsXeLAEiQsDlZ4HBNKYXIIIsLqOxLy5qaTBw08345InPRHSGixInlLMW+Cx3bTB/BISRMmclqEtm6ly52X+G43erSYAa4WH7TlWuTLNNWe0qNnj+jeOhWcxx7DpUqaZ5e7C7FnJfoyLGHdylX55aGC5j+RbkodAoBFwRgXp6tnO75FO7lZJtbDn1XunIAWKCsTct1phpzPKXdGsSHVeHHZMWxGB/3vyS4XHHPFu+1I0k1XZlNuwfHuQDdz7yRxp4P0M7uYw14JUmwzyEiUkTSeGInwuUmHCsBhVeBWgywcOz8WJ413yRESQWe4DwVEQLnrWaLBWw4mtq9TinzQ3yWGg91+k2XzjctFCLSP1vxMu40NFklaQ0+9OneCXq5ZZ1wglSe9We1P/a1s6BRq0oh96ywQ7VLhQYZsg/ofu0D0Ap8kb2Sb85vylNRApojZuxcap5wy+NtJ2AyRHrBHSyITjX5U7RlBdNhJmRDYYDnZUTQgoe+04BilHMIHMg6xxSCx4zSfz1GMGJfKbMzfLU1kydNcxD9hqWJ0f50VCdXya0l9d0Lqc13XZoU7ptRkEsPZ2Si+4QXbJsThw1ZNwYZsBCllNd+YVpOTVKgOoaLwuJ/0FyHI06pQvkFUSQcuPP5tqZR3y/iIPswjUpWxpqgap6UfMumnHz2TPYpYvsAaY2EMts1F+LOx9wujSCPdf7v
    registrationToken: AgCidhjwDoPv7WI0ZmY6VJvBPbe+eJ5jiewBwkWlZCGG8/TQmCvLFhn/pt676Gc0LCbHrEwpOPUQLRLeyQaCnbVuLOJEq+0IvKrfY+UzVYPW2U3l85F3QQKanYIXpCsGjwXnWb6PqsDPS+RjRX3AcMnd7+09VfmVF6QvUwN5TE7LOrttESLSj1HVkUT/13ymu+0OU6A1AQblTbTuANTgqVe2QGT/ErlM/6fFGHP20JCd1+gEK4LQnzFo1aqXFHPYySkD+cg4vjSond+L1GQe5bwDOcYwqkTTVo820rhcVAJ39MHKDbrocabB7fWsdyZ2o5aQTzd3SmSEY548FxJ8lPMBc2B3UMKTCupx4PR30RCuFRKrpf1NoNyPVH1ZW7C7eZhGhmhVrBpiHZ+sch2DRKysTPasxAdx7XwvOvtkqXWTn7yYwXKtpIK8654V/xeksPzDTAveonTvAv7qE22UHPzaWnv/jrnYJHf0LpBYIaAoe7547Jc0O3SoaQ9jqFgtih6CZyH0LapGdqXNIRJz0b031R+J3ll5I3vyEJ5AYOx8dbhip41qKWYzFmB2GJdxoAvxHoQD1uBreBIMl+7U9Z4phhMNoHJDym9ipcVfoNrhZLyXKKtDw8h0nJ9p0/+Wd2q7cgHh8GnrAilQBy7wwOzRNgWqtDOzeriBCP+VhbcbbtV/JtX0kg/fpFL6Qscadr7VDqTQsl8rRnOPY7rBKf+8hyz8yhDMmjCglEtMDHdZNxbtJr/fZYMMJXrHTn0MkIcMRCieipegOkoVhZpaj8h3
  template:
    metadata:
      name: crowdsec-lapi-secrets-external
      namespace: crowdsec
    type: Opaque
