---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-key
  namespace: crowdsec
spec:
  encryptedData:
    BOUNCER_KEY_traefik: AgB9o1ePsSTDmyuPaSHfWG0IXsvn0r2Trv73e449SrOLs4QXajput/RbTGGLzmGkuDqGre5Kf6ZddRtVcMe+6vviqqpFqF5uE7ihN4gZkxdpPFpQ3mVNVQVRlL7Rvr/ElOUP7+L44UVSUf0mnJnN0uWL0AGzfC4YLZoRP8lZA/K7cgXGWHkY0/nCLxPguUzLz0ITTbzJKj7GqgwWebRyuiBz676As2y+ugZy/N+Uzat5QTostURl+g44yCeI74dDEN4IKbkhkjlzJtKiClSjntq4WZjG0/e+ovgRBzqpdXL3+WLZiNZHBK+CmMSjOxO7uMI0N8pXAgcyjIMQJ1g/0TIvSojEWmsHv/SmElkknmJFlvxTTJmvXvo0Wx1iDkwhwJ0aFVQJ4s6q2KawakppUTBnq2QuFaLdHQ0kP++NNfKv3X/SYIoQL68igaSYeUv57zVlFdVRIMF3PHats69iaqMeKiRGJuO7ZdqZEVa5fD46XHXfoPFJGiMW02Ds3JH+a/pfEwgF1xA8w7ugqqsLlSKPtQWnUgQBvSP8D+GRpJEPrnisSoNcIBDUH9mthaBhyLYLk4ERRhi26FDR5AI+U6YmYdw5ogEyPMuxhWXXQV5g4qtcaob1OMoajt4L+Az3UtkC6D5K/nUPW4WDr1GbnqrySRMJMvrG4/AoIdp0krziHe5zQLFsOlLYQQWbi2mcKHQZ/TsVEAbXMZeaaUZBsV3HRanOqTeIiWL+tktajA4nW0E/Lw1ualjxK9Jsm8Sp4pntFHkF9AKcwzHGFexO04dA
  template:
    metadata:
      name: crowdsec-key
      namespace: crowdsec
    type: Opaque
