apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secrets.yaml
  - rook-ceph/rook-ceph.yaml
  - rook-ceph/rook-ceph-resource.yaml
  - database/galera.yaml
  - database/galera-resource.yaml
  - database/redis.yaml
  - crowdsec.yaml
  - monitoring/prometheus.yaml
  - monitoring/prometheus-adapter.yaml
  - monitoring/prometheus-resource.yaml
  - monitoring/loki.yaml
  - monitoring/loki-resource.yaml
  - monitoring/alloy.yaml
  - monitoring/grafana.yaml
  - monitoring/grafana-resource.yaml
