apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my.cnf: | 
        [client]
        default-character-set = utf8mb4
 
        [mysql]
        default-character-set = utf8mb4
 
        [mysqld]
        character-set-server           = utf8mb4
        #collation-server               = utf8mb4_unicode_ci
        #
        bind-address = 0.0.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql-deploy
      tier: mysql-back
  template:
    metadata:
      labels:
        app: mysql-deploy
        tier: mysql-back
    spec:
      containers:
      - image: mysql:latest
        name: mysql-image
        env:         
        - name: MYSQL_HOST
          value: localhost
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-info
              key: root_password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-info
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-info
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-info
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-v-config
          mountPath: /etc/mysql/conf.d/     
      volumes:
      - name: mysql-v-config
        configMap: 
          name: mysql-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: wordpress
spec:
  selector:
    app: mysql-deploy
    tier: mysql-back
  ports:
  - port: 3306
