apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-rgw-loki-store
  namespace: rook-ceph
  labels:
    app: rook-ceph-rgw
    rook_cluster: rook-ceph
    rook_object_store: loki-store
spec:
  type: ClusterIP
  ports:
    - name: rgw
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: rook-ceph-rgw
    rook_cluster: rook-ceph
    rook_object_store: loki-store

