apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-worker-bouncer
  namespace: crowdsec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-worker-bouncer
  template:
    metadata:
      labels:
        app: cloudflare-worker-bouncer
    spec:
      containers:
        - name: bouncer
          image: crowdsecurity/cloudflare-worker-bouncer:v0.0.14
          args: ["-c", "/etc/crowdsec/bouncers/crowdsec-cloudflare-worker-bouncer.yaml"]
          envFrom:
            - secretRef:
                name: cloudflare-worker-bouncer-secret
          volumeMounts:
            - name: cfg
              mountPath: /etc/crowdsec/bouncers
          ports:
            - name: metrics
              containerPort: 2112
      volumes:
        - name: cfg
          configMap:
            name: cloudflare-worker-bouncer-config
            items:
              - key: crowdsec-cloudflare-worker-bouncer.yaml
                path: crowdsec-cloudflare-worker-bouncer.yaml

