prometheus:
  url: http://kube-prometheus-stack-prometheus.monitoring.svc
  port: 9090

rules:
  default: false
  external:
    - seriesQuery: 'traefik_service_requests_total{k8s_namespace!=""}'
      resources:
        overrides:
          k8s_namespace: {resource: "namespace"}
      name:
        as: "traefik_service_rps"
      metricsQuery: |
        sum by (k8s_namespace) (
          rate(traefik_service_requests_total{
            k8s_namespace="monitoring",
            k8s_service="grafana"
          }[2m])
        )
