apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-worker-bouncer-secret
  namespace: crowdsec
type: Opaque
stringData:
  CF_API_TOKEN: "<CLOUDFLARE_USER_API_TOKEN>"
  CROWDSEC_LAPI_KEY: "<CROWDSEC_BOUNCER_KEY>"
  CF_ACCOUNT_ID: "<CLOUDFLARE_ACCOUNT_ID>"
  CF_ZONE_ID: "<CLOUDFLARE_ZONE_ID>"
