apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: traefik
type: Opaque
stringData:
  # 여기에 실제 토큰값을 그대로 적으세요. (K8s가 알아서 인코딩함)
  CF_DNS_API_TOKEN: "fPjw7b6s355V7v9FYJoxgZw-NoN-48Sbv8XMzmQY"
