apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/lucky-gun/kubernetes
    - https://traefik.github.io/charts
    - https://charts.jenkins.io
  destinations:
    - server: https://kubernetes.default.svc
      namespace: traefik
    - server: https://kubernetes.default.svc
      namespace: jenkins
    - server: https://kubernetes.default.svc
      namespace: monitoring
    - server: https://kubernetes.default.svc
      namespace: rook-ceph
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: apps
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
