apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: security
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/lucky-gun/kubernetes
    - https://crowdsecurity.github.io/helm-charts
    - https://kyverno.github.io/kyverno
    - https://bitnami-labs.github.io/sealed-secrets
  destinations:
    - server: https://kubernetes.default.svc
      namespace: security
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
