apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: storage
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/lucky-gun/kubernetes
    - https://charts.rook.io/release
  destinations:
    - server: https://kubernetes.default.svc
      namespace: rook-ceph
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
