prometheus:
  url: http://prometheus-stack-kube-prom-prometheus.monitoring.svc
  port: 9090
  path: ""

rules:
  default: false 
  external:
    - seriesQuery: 'traefik_service_requests_total{service="traefik-metrics",exported_service!=""}'
      name:
        matches: '^traefik_service_requests_total$'
        as: 'traefik_k8s_service_rps'
      metricsQuery: >
        sum by (k8s_service) (
          label_replace(
            rate(traefik_service_requests_total{service="traefik-metrics"}[1m]),
            "k8s_service", "$1",
            "exported_service", "^(.*)@kubernetescrd$"
          )
        )

