---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-secret
  namespace: database
spec:
  encryptedData:
    password: AgADC6/Z///tB76MWHAjFDTRuHae8R/CPunPrwPO0iVPFMhaKiJ1CTJLlY/VKnC9fq1y2+tV17KlfbF5QT18m0ap2vwU2L5AUuwF11eVUOH2ZgdnURnnuFZdi/FL80P7b00WnHo+dDbQbKHwkgw5KfYEKmhyIO94KeZNrPfk8kNqgp3RAKC7YImBuoN1UnTmfrCvFNHyjUFdUVWQ9EjC9j8/awsW/wudqREyz0c6pmkXdE+fwVjLKxpmKsHr6lvB2wq21KuxEwQHTpWvpvaGalWHxW3iIeUpGlIk+R2RvMz4x19Ibq5FlJmSRN+sAb4dUSel33J5wUtyA+XbUIKXOQDVi30B5xkol9MMPG4izNe4ga5FYLBVck7wY09DRnFrFQoyfJV1m42/KB5gy4dt0wciR8A/RkAJitznJ+f/9ueWjabuHkBguxr6cN5Wc7V1fh/x6L9Vc0JeNfmMGW/YrYMeJqfBAPovetDc20y+nszxFlxovzFjALKFkcZEundNC0JQrs9yypRCqkzoaZX/+iN49iCwb9kMFPlrTNblf+9JZWYIgT5Z3VEoI0ERys40lZdZbPDuDi9TmjX9ZqD0jWfzG6e0gcEansKSy7VRECDChE4E0m9CHfi+PiuzPC7w2NYpYBf/vEIkBS4K3fRCXO/Adxo6bUb7Rc43aR2/3wpULai2S3wLjzn3L4+gOgsQxUIuP47uEDlitRo=
  template:
    metadata:
      name: mariadb-secret
      namespace: database
    type: Opaque
