apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-api-proxy
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-proxy
  template:
    metadata:
      labels:
        app: api-proxy
    spec:
      containers:
        - name: proxy
          image: ghcr.io/nextcloud/nextcloud-appapi-dsp:release
          env:
            - name: NC_HAPROXY_PASSWORD
              value: ""
          ports:
            - containerPort: 2375
          volumeMounts:
            - name: containerd-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: containerd-sock
          hostPath:
            path: /var/run/containerd/containerd.sock
            type: Socket

---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-api-proxy-service
  namespace: infra
spec:
  selector:
    app: api-proxy
  ports:
    - port: 2375
      targetPort: 2375
