apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-bouncer-key
  namespace: traefik
type: Opaque
stringData:
  CROWDSEC_LAPI_KEY: "fa2ac7dd1524da75012298810a89811a64ffc4aacb845c25c4445f3d7e8ef964"
