apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    # Let's Encrypt 서버 URL
    server: https://acme-v02.api.letsencrypt.org/directory
    email: fallsky104@naver.com  # 인증서 갱신 알림을 받을 이메일 주소
    privateKeySecretRef:
      name: letsencrypt-prod-account-key  # 개인 키를 저장할 Secret 이름
    solvers:
      - http01:
          ingress:
            class: ingress-nginx  # Ingress Controller로 Nginx를 사용

