apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argo

data:
  scopes: "[groups]"

  policy.default: role:none

  policy.csv: |
    p, role:none, *, *, */*, deny

    g, argocd-admin, role:admin
    g, argocd-viewer, role:readonly
