---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: traefik
spec:
  encryptedData:
    CROWDSEC_LAPI_KEY: AgBmjLOKCQTbEm2JvBbIeznljcBjOe28aShxOc1kvuXBuYYqdzHxubgRRmxPKY1HLAc0TRJe+/tQ0A0XRHE/hRYTZez/nlys4AsWqpf3My5xgEH1KugTqsgq8/PI28LRUcQQ4q0A52kuaw+Cwr1/aPR/dbpFqLgYz26AOl2qrv9C418IQXl+mxjN4NVxlM3+eNZQzF04568EMmIxBekYeRwTk2Hh2mdXdJeJKcNoctqdnh8U7du+Z0ieUwGTBj6hIpXxIbko5Q7RGz5huAtNhU6Mxy7A+07PLryKJZlx1bT9KaXWfh+u8TFHHemLQRvoVgKv2ZyOzxwCyWOTKmXnppSXCfK6VXDW8PHffTXcOxOSGRQdvdhWyXABkHhvoCdtRr8DaQS6SHt53/kTa/0TuzvRvN+ARMJSrlTJf3uYlRyzW9ysIJ+9tyN50uK3T5dcprpXUxc7bkE+VVtwDsrMcPz5Cfwx2W/vn8u256FyCkzHlQP5Yq6b4717lptpdB8k3QcKB0uISZyLViYqZXzWwPs5kkGiYQkQNH8vkEDX6kJv800lvUF29S/8EsRy2DNkoW4l5M4vSB9l59wmyXgZfnSZ3KnWgtxSwhgmpFeAh3wikPAfBmR6yHwiOzJXhSaavyD1OZZDWmj8qUQQ/uXUuFfzeLKCyoM74/CpGkyY+p9tMJKEI3xoPIopLufc3R3RtCCH0Qx7N5rmV5923FWOiyUSOr1ryp0cTXKneTnRl6+VNgJ3IcumW//dagSqjSx+dz8qX6UVIjgxQdXix02O3SEo
  template:
    metadata:
      name: crowdsec-bouncer-key
      namespace: traefik
    type: Opaque
