---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: traefik
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgBYEL07scqa3yxm2sFPNxAaLXU4i+rtcS3DspZuYiIuokW38CiNX6o5yYa5IIPC4MKVwKaA9rN66Ybsk5cw1zN1BMxrtfe/1gzqXEumIKQ6AOocqSNeLw0WlI8f2oBFu0f7plFS3SCqLfE8FWCfoqSL5kUqsO65o62oWYq2NcET1MLDqbU371kTGFXC3uNwMSByCT6cJ5oCa2bc31lHp9+5k/7aylf+OJWqEdK9qFORgA/fifBoMrWrRavxEFUCVBWLdvel6thu7IHJ2ntvGJoabwe8B0y84RpoWlin0asQo/1dApssa8N5CfDCTb/5ejN0OEQ/Bis90CF3IwNj183ZIUG/XVKYzUm4xcPbwzDcJyAUhCIIcKwTljxe4eN5zsObikOwINKiAUrdJ9C3v9HiDtsG/r6Sm4cGmYJxxFMXkFXa+OZlDo4FFmiBeZgoNFAlJsPXGGnmwBIerB17tRt33rTIxnCuC9ptJg5FzGZJMwUDcpb+uDEnOPBWFlqJXsjZM2dbe4Znr1TVmfVts+LecraiBxSDg7z4BEcodhkFyuEtgaaCazVearRwulN1J/mH8pRv8jsJRlkFoWC0b5PyFDHv6D8EVP5WOxaeW2x5FTmDGMTN4Cx9KirAGE48KMdq5pgi5jQE8tuWagoEG6SZejPRKFOpFRibnF/6z4rf7Nb6PKSLblZDXuvcwgO+HED13lecueZcVS9CC3HryKZMDYbsc27qdmbZqgZahaB3/z1dCqmDxAaG
  template:
    metadata:
      name: cloudflare-api-token
      namespace: traefik
    type: Opaque
