apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rook-cluster.yaml
  - rook-rbd.yaml
  - rook-rbd-storageclass.yaml
  - rook-cephfs.yaml
  - rook-cephfs-storageclass.yaml
  - rook-objectstore.yaml
