apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: monitoring
  source:
    repoURL: https://github.com/lucky-gun/kubernetes
    targetRevision: main
    path: my-website/gitops/infrastructure/monitoring/prometheus/metadata
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
