apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra

# Secret 자동 생성기
secretGenerator:
- name: wordpress-db-secrets
  envs:
  - .env

configMapGenerator:
- name: wordpress-config
  literals:
    - db_host=mariadb-galera.database.svc.cluster.local
    - wp_tz=Asia/Seoul

# 적용할 리소스들
resources:
- wordpress.yaml
