# 1. Prometheus 관련 설정 (Rules & Scrape)
prometheus:
  prometheusSpec:
    # 사용자 정의 룰(PrometheusRule)을 인식하도록 설정
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    
    # 외부 타겟(기존 Docker 환경 잔재 등)이 있다면 여기에 추가 가능
    # (현재는 K8s 내부용이라 하셔서 비워둠)
    additionalScrapeConfigs: []

# 2. Alertmanager 관련 설정 (알람 전송)
alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: "slack-default"
      group_by: ['service', 'alertname']
      group_wait: 2m
      group_interval: 15m
      repeat_interval: 4h
      routes:
        - receiver: "slack-once"
          matchers:
            - service="secops"
          group_by: ['service', 'alertname']
          group_wait: 10s
          group_interval: 10s
          repeat_interval: 999h
        - receiver: "slack-once"
          matchers:
            - service="infra"
          group_by: ['service', 'alertname']
          group_wait: 10s
          group_interval: 10s
          repeat_interval: 999h
    receivers:
      - name: "slack-default"
        slack_configs:
          - send_resolved: true
            channel: "skill-up"
            username: "Alert"
            icon_emoji: "⚓"
            text: |-
              [{{ .Status | toUpper }}] {{ (index .Alerts 0).Labels.alertname }}
              Summary: {{ (index .Alerts 0).Annotations.summary }}
              Description: {{ (index .Alerts 0).Annotations.description }}
      - name: "slack-once"
        slack_configs:
          - send_resolved: false
            channel: "skill-up"
            username: "Alert"
            icon_emoji: "⚓"
            text: |-
              [{{ .Status | toUpper }}] {{ (index .Alerts 0).Labels.alertname }}
              Summary: {{ (index .Alerts 0).Annotations.summary }}
              Description: {{ (index .Alerts 0).Annotations.description }}
    inhibit_rules:
      - source_match:
          severity: "critical"
          service: "infra"
        target_match:
          severity: "warning"
          service: "infra"
        equal: ["instance"]

# 3. Grafana 관련 설정 (시각화)
grafana:
  enabled: true
  adminUser: luckygun1004
  adminPassword: "rlckrlrhkstk104!"
  
  grafana.ini:
    server:
      domain: grafana.lucky-gun.com
      root_url: https://grafana.lucky-gun.com/
      serve_from_sub_path: false
    auth.anonymous:
      enabled: true
      org_name: "Main Org."
      org_role: Viewer
    auth:
      disable_login_form: false
      login_maximum_inactive_lifetime_days: 30
      login_maximum_lifetime_days: 30
    users:
      allow_sign_up: false
    security:
      allow_embedding: true
      cookie_samesite: lax
      x_content_type_options: true
      x_xss_protection: true

  persistence:
    enabled: true
    type: pvc
    size: 10Gi

  ingress:
    enabled: true
    ingressClassName: nginx # 혹은 traefik
    hosts:
      - grafana.lucky-gun.com
    path: /
