---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack
  namespace: monitoring
spec:
  encryptedData:
    slack_api_url: AgCYqOl6q6LZa3tYrgJa257PwfypM+G/O9CQdSOgV5sQZGwmu697lr9He7ZIebiJDkiuC7HCUv3lVoj9q6XWawEICvkHQ7G6d2OPXYoOsv5774zH+dEAHGpJHu5nbLPKgizzvmvGnjxhWH8517pNUUYBu+ETL6jy9U9IbdtOKcE7SUWTobv/WoCM/h0fNkFYdwlmIegmhpnZV/Tplk9VFWnQ9lB+TVb47osMlWHQ1G+Hz8LS2y8HUb8EL1OSs37K9LybeT0B9iFmVHF9WpBlM6DTUnKX5CE4hqMAJHh3iFLtIRFZrfdGrUgQ3JoqaWjxO1VwisdQhuyV6ioR105VCTEfjhx020jFCpomaj2+MWNSJBbAW0oKjQY20fILKrEFL+6e6tLJz6DOGyRi10sBHFtHq7JsLZpR6DOL2/0QFSeIveRfKPa0mZzo1LD6zpkTv9663y6f6ICQD+27qp6r8NutmSO6VAWyiDdBFAlxvAWIs8/uqBMTAPsbQRFOvsdCJNWh719vGMy8yoxEsSUNuESejFz8oPJTwEBU1jsFBOcEQZ67+rN4X26DFnIuWfrGua19e89m8Gce/ObmVBFc9kM63lu6A14jxqEk2NoMFM4TxLEuL6BjwQi28g9QVcHhv46QVJ+K44OnrQGpKoGnLTsmbcl9JXtRyZUTl/ZzufxCC7rEemASS8xxA+NmoGS0zQZAjPm0JDVdpjaloWyFtEZzv1rt1cULCjU1a2xoehWL8frpeliPG767igARCqOnp/WKbA30+g1Y7JxTIDdlG0PrENGd/pDrA2STlOLQYbcAoyc=
  template:
    metadata:
      name: alertmanager-slack
      namespace: monitoring
    type: Opaque
