apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki
  namespace: infra
  labels:
    app: mediawiki
spec:
  replicas: 1   # 🔹 여기만 나중에 3으로 변경
  selector:
    matchLabels:
      app: mediawiki
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
        - name: mediawiki
          image: luckygun/mediawiki:myblog-beta
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 80

          volumeMounts:
            - name: mediawiki-storage
              mountPath: /var/www/html/images
              subPath: images

            #설정된 이후 작업 진행
            #- name: localsettings
            #  mountPath: /var/www/html/LocalSettings.php
            #  subPath: LocalSettings.php
            #  readOnly: true

      volumes:
        - name: mediawiki-storage
          persistentVolumeClaim:
            claimName: mw-shared-pvc

        #- name: localsettings
        #  secret:
        #    secretName: mediawiki-localsettings

---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki-service
  namespace: infra
spec:
  selector:
    app: mediawiki
  ports:
    - port: 80
      targetPort: 80
