apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJsdWNreWd1biIsInBhc3N3b3JkIjoiZGNrcl9wYXRfUUU2ZktkcDJIajNOSzBYZFlHOU0zdEJvYVZ3IiwiZW1haWwiOiJmYWxsc2t5MTA0QGdtYWlsLmNvbSIsImF1dGgiOiJiSFZqYTNsbmRXNDZaR05yY2w5d1lYUmZVVVUyWmt0a2NESklhak5PU3pCWVpGbEhPVTB6ZEVKdllWWjMifX19
kind: Secret
metadata:
  name: regcred
  namespace: infra
type: kubernetes.io/dockerconfigjson
