apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
    grafana_datasource: "1"
  #annotations:
  #  k8s-sidecar-target-directory: /tmp/dashboards/loki
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        uid: P8E80F9AEF21F6940
        type: loki
        access: proxy
        url: http://loki-gateway.monitoring.svc.cluster.local
        isDefault: false
      - name: Prometheus
        uid: PBFA97CFB590B2093
        type: prometheus
        access: proxy
        url: http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090
        isDefault: true
