apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: 
    tls.key:
  kind: Secret
  metadata:
    creationTimestamp: "2026-01-27T12:31:09Z"
    generateName: sealed-secrets-key
    labels:
      sealedsecrets.bitnami.com/sealed-secrets-key: active
    name: sealed-secrets-keybc7xq
    namespace: kube-system
    resourceVersion: "245202"
    uid: f2cddfe9-8e86
  type: kubernetes.io/tls
kind: List
metadata:
  resourceVersion: ""
