apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-node-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
  - name: node_status_alerts_custom
    rules:
      - alert: HostDownCustom
        expr: up == 0
        for: 2m
        labels:
          severity: critical
          service: infra
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "Prometheus could not scrape {{ $labels.job }} on {{ $labels.instance }} for 2 minutes."

  - name: node_resource_alerts_custom
    rules:
      - alert: HighCPUUsageCustom
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 85
        for: 5m
        labels:
          severity: warning
          service: infra
        annotations:
          summary: "High CPU on {{ $labels.instance }}"
          description: "CPU usage > 85% for 5m"

      - alert: DiskSpaceLowCustom
        expr: (node_filesystem_avail_bytes{fstype!~"tmpfs|overlay"} / node_filesystem_size_bytes{fstype!~"tmpfs|overlay"}) < 0.1
        for: 10m
        labels:
          severity: warning
          service: infra
        annotations:
          summary: "Low disk space on {{ $labels.instance }}"
          description: "Free disk space < 10% for 10m"
