uapiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-resources
  namespace: argocd
spec:
  project: storage
  source:
    repoURL: https://github.com/lucky-gun/kubernetes
    targetRevision: main
    path: my-website/gitops/infrastructure/rook-ceph/metadata
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

