apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
spec:
  project: storage
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  sources:
    - repoURL: https://charts.rook.io/release
      chart: rook-ceph
      targetRevision: 1.19.0
      helm:
        valueFiles:
          - $values/my-website/gitops/infrastructure/rook-ceph/values.yaml
    - repoURL: https://github.com/lucky-gun/kubernetes
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

